import pandas as pd

# Define the dataset as a list of dictionaries
data = [
    {"Country": "Afghanistan", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Albania", "Most Recent Year": 2020, "Most Recent Value": 29.4},
    {"Country": "Algeria", "Most Recent Year": 2011, "Most Recent Value": 27.6},
    {"Country": "American Samoa", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Andorra", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Angola", "Most Recent Year": 2018, "Most Recent Value": 51.3},
    {"Country": "Antigua and Barbuda", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Argentina", "Most Recent Year": 2022, "Most Recent Value": 40.7},
    {"Country": "Armenia", "Most Recent Year": 2022, "Most Recent Value": 27.9},
    {"Country": "Aruba", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Australia", "Most Recent Year": 2018, "Most Recent Value": 34.3},
    {"Country": "Austria", "Most Recent Year": 2021, "Most Recent Value": 30.7},
    {"Country": "Azerbaijan", "Most Recent Year": 2005, "Most Recent Value": 26.6},
    {"Country": "Bahamas, The", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Bahrain", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Bangladesh", "Most Recent Year": 2022, "Most Recent Value": 33.4},
    {"Country": "Barbados", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Belarus", "Most Recent Year": 2020, "Most Recent Value": 24.4},
    {"Country": "Belgium", "Most Recent Year": 2021, "Most Recent Value": 26.6},
    {"Country": "Belize", "Most Recent Year": 1999, "Most Recent Value": 53.2},
    {"Country": "Benin", "Most Recent Year": 2021, "Most Recent Value": 34.4},
    {"Country": "Bermuda", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Bhutan", "Most Recent Year": 2022, "Most Recent Value": 28.5},
    {"Country": "Bolivia", "Most Recent Year": 2021, "Most Recent Value": 40.9},
    {"Country": "Bosnia and Herzegovina", "Most Recent Year": 2011, "Most Recent Value": 33.0},
    {"Country": "Botswana", "Most Recent Year": 2015, "Most Recent Value": 53.3},
    {"Country": "Brazil", "Most Recent Year": 2022, "Most Recent Value": 52.0},
    {"Country": "British Virgin Islands", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Brunei Darussalam", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Bulgaria", "Most Recent Year": 2021, "Most Recent Value": 39.0},
    {"Country": "Burkina Faso", "Most Recent Year": 2021, "Most Recent Value": 37.4},
    {"Country": "Burundi", "Most Recent Year": 2020, "Most Recent Value": 37.5},
    {"Country": "Cabo Verde", "Most Recent Year": 2015, "Most Recent Value": 42.4},
    {"Country": "Cambodia", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Cameroon", "Most Recent Year": 2021, "Most Recent Value": 42.2},
    {"Country": "Canada", "Most Recent Year": 2019, "Most Recent Value": 31.7},
    {"Country": "Cayman Islands", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Central African Republic", "Most Recent Year": 2021, "Most Recent Value": 43.0},
    {"Country": "Chad", "Most Recent Year": 2022, "Most Recent Value": 37.4},
    {"Country": "Channel Islands", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Chile", "Most Recent Year": 2022, "Most Recent Value": 43.0},
    {"Country": "China", "Most Recent Year": 2021, "Most Recent Value": 35.7},
    {"Country": "Colombia", "Most Recent Year": 2022, "Most Recent Value": 54.8},
    {"Country": "Comoros", "Most Recent Year": 2014, "Most Recent Value": 45.3},
    {"Country": "Congo, Dem. Rep.", "Most Recent Year": 2020, "Most Recent Value": 44.7},
    {"Country": "Congo, Rep.", "Most Recent Year": 2011, "Most Recent Value": 48.9},
    {"Country": "Costa Rica", "Most Recent Year": 2023, "Most Recent Value": 46.7},
    {"Country": "Cote d'Ivoire", "Most Recent Year": 2021, "Most Recent Value": 35.3},
    {"Country": "Croatia", "Most Recent Year": 2021, "Most Recent Value": 28.9},
    {"Country": "Cuba", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Curacao", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Cyprus", "Most Recent Year": 2021, "Most Recent Value": 31.3},
    {"Country": "Czechia", "Most Recent Year": 2021, "Most Recent Value": 26.2},
    {"Country": "Denmark", "Most Recent Year": 2021, "Most Recent Value": 28.3},
    {"Country": "Djibouti", "Most Recent Year": 2017, "Most Recent Value": 41.6},
    {"Country": "Dominica", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Dominican Republic", "Most Recent Year": 2022, "Most Recent Value": 37.0},
    {"Country": "Ecuador", "Most Recent Year": 2023, "Most Recent Value": 44.6},
    {"Country": "Egypt, Arab Rep.", "Most Recent Year": 2019, "Most Recent Value": 31.9},
    {"Country": "El Salvador", "Most Recent Year": 2022, "Most Recent Value": 38.8},
    {"Country": "Equatorial Guinea", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Eritrea", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Estonia", "Most Recent Year": 2021, "Most Recent Value": 31.8},
    {"Country": "Eswatini", "Most Recent Year": 2016, "Most Recent Value": 54.6},
    {"Country": "Ethiopia", "Most Recent Year": 2015, "Most Recent Value": 35.0},
    {"Country": "Faroe Islands", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Fiji", "Most Recent Year": 2019, "Most Recent Value": 30.7},
    {"Country": "Finland", "Most Recent Year": 2021, "Most Recent Value": 27.7},
    {"Country": "France", "Most Recent Year": 2021, "Most Recent Value": 31.5},
    {"Country": "French Polynesia", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Gabon", "Most Recent Year": 2017, "Most Recent Value": 38.0},
    {"Country": "Gambia, The", "Most Recent Year": 2020, "Most Recent Value": 38.8},
    {"Country": "Georgia", "Most Recent Year": 2022, "Most Recent Value": 33.5},
    {"Country": "Germany", "Most Recent Year": 2020, "Most Recent Value": 32.4},
    {"Country": "Ghana", "Most Recent Year": 2016, "Most Recent Value": 43.5},
    {"Country": "Gibraltar", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Greece", "Most Recent Year": 2021, "Most Recent Value": 32.9},
    {"Country": "Greenland", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Grenada", "Most Recent Year": 2018, "Most Recent Value": 43.8},
    {"Country": "Guam", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Guatemala", "Most Recent Year": 2014, "Most Recent Value": 48.3},
    {"Country": "Guinea", "Most Recent Year": 2018, "Most Recent Value": 29.6},
    {"Country": "Guinea-Bissau", "Most Recent Year": 2021, "Most Recent Value": 33.4},
    {"Country": "Guyana", "Most Recent Year": 1998, "Most Recent Value": 45.0},
    {"Country": "Haiti", "Most Recent Year": 2012, "Most Recent Value": 41.1},
    {"Country": "Honduras", "Most Recent Year": 2019, "Most Recent Value": 48.2},
    {"Country": "Hong Kong SAR, China", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Hungary", "Most Recent Year": 2021, "Most Recent Value": 29.2},
    {"Country": "Iceland", "Most Recent Year": 2017, "Most Recent Value": 26.1},
    {"Country": "India", "Most Recent Year": 2021, "Most Recent Value": 32.8},
    {"Country": "Indonesia", "Most Recent Year": 2023, "Most Recent Value": 36.1},
    {"Country": "Iran, Islamic Rep.", "Most Recent Year": 2022, "Most Recent Value": 34.8},
    {"Country": "Iraq", "Most Recent Year": 2012, "Most Recent Value": 29.5},
    {"Country": "Ireland", "Most Recent Year": 2021, "Most Recent Value": 30.1},
    {"Country": "Isle of Man", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Israel", "Most Recent Year": 2021, "Most Recent Value": 37.9},
    {"Country": "Italy", "Most Recent Year": 2021, "Most Recent Value": 34.8},
    {"Country": "Jamaica", "Most Recent Year": 2021, "Most Recent Value": 40.2},
    {"Country": "Japan", "Most Recent Year": 2013, "Most Recent Value": 32.9},
    {"Country": "Jordan", "Most Recent Year": 2010, "Most Recent Value": 33.7},
    {"Country": "Kazakhstan", "Most Recent Year": 2021, "Most Recent Value": 29.2},
    {"Country": "Kenya", "Most Recent Year": 2021, "Most Recent Value": 38.7},
    {"Country": "Kiribati", "Most Recent Year": 2019, "Most Recent Value": 27.8},
    {"Country": "Korea, Dem. People's Rep.", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Korea, Rep.", "Most Recent Year": 2021, "Most Recent Value": 32.9},
    {"Country": "Kosovo", "Most Recent Year": 2017, "Most Recent Value": 29.0},
    {"Country": "Kuwait", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Kyrgyz Republic", "Most Recent Year": 2022, "Most Recent Value": 26.4},
    {"Country": "Lao PDR", "Most Recent Year": 2018, "Most Recent Value": 38.8},
    {"Country": "Latvia", "Most Recent Year": 2021, "Most Recent Value": 34.3},
    {"Country": "Lebanon", "Most Recent Year": 2011, "Most Recent Value": 31.8},
    {"Country": "Lesotho", "Most Recent Year": 2017, "Most Recent Value": 44.9},
    {"Country": "Liberia", "Most Recent Year": 2016, "Most Recent Value": 35.3},
    {"Country": "Libya", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Liechtenstein", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Lithuania", "Most Recent Year": 2021, "Most Recent Value": 36.7},
    {"Country": "Luxembourg", "Most Recent Year": 2021, "Most Recent Value": 32.7},
    {"Country": "Macao SAR, China", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Madagascar", "Most Recent Year": 2012, "Most Recent Value": 42.6},
    {"Country": "Malawi", "Most Recent Year": 2019, "Most Recent Value": 38.5},
    {"Country": "Malaysia", "Most Recent Year": 2021, "Most Recent Value": 40.7},
    {"Country": "Maldives", "Most Recent Year": 2019, "Most Recent Value": 29.3},
    {"Country": "Mali", "Most Recent Year": 2021, "Most Recent Value": 35.7},
    {"Country": "Malta", "Most Recent Year": 2020, "Most Recent Value": 31.4},
    {"Country": "Marshall Islands", "Most Recent Year": 2019, "Most Recent Value": 35.5},
    {"Country": "Mauritania", "Most Recent Year": 2019, "Most Recent Value": 32.0},
    {"Country": "Mauritius", "Most Recent Year": 2017, "Most Recent Value": 36.8},
    {"Country": "Mexico", "Most Recent Year": 2022, "Most Recent Value": 43.5},
    {"Country": "Micronesia, Fed. Sts.", "Most Recent Year": 2013, "Most Recent Value": 40.1},
    {"Country": "Moldova", "Most Recent Year": 2021, "Most Recent Value": 25.7},
    {"Country": "Monaco", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Mongolia", "Most Recent Year": 2022, "Most Recent Value": 31.4},
    {"Country": "Montenegro", "Most Recent Year": 2021, "Most Recent Value": 34.3},
    {"Country": "Morocco", "Most Recent Year": 2013, "Most Recent Value": 39.5},
    {"Country": "Mozambique", "Most Recent Year": 2019, "Most Recent Value": 50.3},
    {"Country": "Myanmar", "Most Recent Year": 2017, "Most Recent Value": 30.7},
    {"Country": "Namibia", "Most Recent Year": 2015, "Most Recent Value": 59.1},
    {"Country": "Nauru", "Most Recent Year": 2012, "Most Recent Value": 32.4},
    {"Country": "Nepal", "Most Recent Year": 2022, "Most Recent Value": 30.0},
    {"Country": "Netherlands", "Most Recent Year": 2021, "Most Recent Value": 25.7},
    {"Country": "New Caledonia", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "New Zealand", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Nicaragua", "Most Recent Year": 2014, "Most Recent Value": 46.2},
    {"Country": "Niger", "Most Recent Year": 2021, "Most Recent Value": 32.9},
    {"Country": "Nigeria", "Most Recent Year": 2018, "Most Recent Value": 35.1},
    {"Country": "North Macedonia", "Most Recent Year": 2019, "Most Recent Value": 33.5},
    {"Country": "Northern Mariana Islands", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Norway", "Most Recent Year": 2019, "Most Recent Value": 27.7},
    {"Country": "Oman", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Pakistan", "Most Recent Year": 2018, "Most Recent Value": 29.6},
    {"Country": "Palau", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Panama", "Most Recent Year": 2023, "Most Recent Value": 48.9},
    {"Country": "Papua New Guinea", "Most Recent Year": 2009, "Most Recent Value": 41.9},
    {"Country": "Paraguay", "Most Recent Year": 2022, "Most Recent Value": 45.1},
    {"Country": "Peru", "Most Recent Year": 2022, "Most Recent Value": 40.3},
    {"Country": "Philippines", "Most Recent Year": 2021, "Most Recent Value": 40.7},
    {"Country": "Poland", "Most Recent Year": 2021, "Most Recent Value": 28.5},
    {"Country": "Portugal", "Most Recent Year": 2021, "Most Recent Value": 34.6},
    {"Country": "Puerto Rico", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Qatar", "Most Recent Year": 2017, "Most Recent Value": 35.1},
    {"Country": "Romania", "Most Recent Year": 2021, "Most Recent Value": 33.9},
    {"Country": "Russian Federation", "Most Recent Year": 2021, "Most Recent Value": 35.1},
    {"Country": "Rwanda", "Most Recent Year": 2016, "Most Recent Value": 43.7},
    {"Country": "Samoa", "Most Recent Year": 2013, "Most Recent Value": 38.7},
    {"Country": "San Marino", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Sao Tome and Principe", "Most Recent Year": 2017, "Most Recent Value": 40.7},
    {"Country": "Saudi Arabia", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Senegal", "Most Recent Year": 2021, "Most Recent Value": 36.2},
    {"Country": "Serbia", "Most Recent Year": 2021, "Most Recent Value": 33.1},
    {"Country": "Seychelles", "Most Recent Year": 2018, "Most Recent Value": 32.1},
    {"Country": "Sierra Leone", "Most Recent Year": 2018, "Most Recent Value": 35.7},
    {"Country": "Singapore", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Sint Maarten (Dutch part)", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Slovak Republic", "Most Recent Year": 2021, "Most Recent Value": 24.1},
    {"Country": "Slovenia", "Most Recent Year": 2021, "Most Recent Value": 24.3},
    {"Country": "Solomon Islands", "Most Recent Year": 2012, "Most Recent Value": 37.1},
    {"Country": "Somalia", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "South Africa", "Most Recent Year": 2014, "Most Recent Value": 63.0},
    {"Country": "South Sudan", "Most Recent Year": 2016, "Most Recent Value": 44.1},
    {"Country": "Spain", "Most Recent Year": 2021, "Most Recent Value": 33.9},
    {"Country": "Sri Lanka", "Most Recent Year": 2019, "Most Recent Value": 37.7},
    {"Country": "St. Kitts and Nevis", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "St. Lucia", "Most Recent Year": 2015, "Most Recent Value": 43.7},
    {"Country": "St. Martin (French part)", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "St. Vincent and the Grenadines", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Sudan", "Most Recent Year": 2014, "Most Recent Value": 34.2},
    {"Country": "Suriname", "Most Recent Year": 2022, "Most Recent Value": 39.2},
    {"Country": "Sweden", "Most Recent Year": 2021, "Most Recent Value": 29.8},
    {"Country": "Switzerland", "Most Recent Year": 2020, "Most Recent Value": 33.7},
    {"Country": "Syrian Arab Republic", "Most Recent Year": 2022, "Most Recent Value": 26.6},
    {"Country": "Tajikistan", "Most Recent Year": 2015, "Most Recent Value": 34.0},
    {"Country": "Tanzania", "Most Recent Year": 2018, "Most Recent Value": 40.5},
    {"Country": "Thailand", "Most Recent Year": 2021, "Most Recent Value": 34.9},
    {"Country": "Timor-Leste", "Most Recent Year": 2014, "Most Recent Value": 28.7},
    {"Country": "Togo", "Most Recent Year": 2021, "Most Recent Value": 37.9},
    {"Country": "Tonga", "Most Recent Year": 2021, "Most Recent Value": 27.1},
    {"Country": "Trinidad and Tobago", "Most Recent Year": 1992, "Most Recent Value": 40.2},
    {"Country": "Tunisia", "Most Recent Year": 2021, "Most Recent Value": 33.7},
    {"Country": "Turkiye", "Most Recent Year": 2021, "Most Recent Value": 44.4},
    {"Country": "Turkmenistan", "Most Recent Year": 1998, "Most Recent Value": 40.8},
    {"Country": "Turks and Caicos Islands", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Tuvalu", "Most Recent Year": 2010, "Most Recent Value": 39.1},
    {"Country": "Uganda", "Most Recent Year": 2019, "Most Recent Value": 42.7},
    {"Country": "Ukraine", "Most Recent Year": 2020, "Most Recent Value": 25.6},
    {"Country": "United Arab Emirates", "Most Recent Year": 2018, "Most Recent Value": 26.4},
    {"Country": "United Kingdom", "Most Recent Year": 2021, "Most Recent Value": 32.4},
    {"Country": "United States", "Most Recent Year": 2022, "Most Recent Value": 41.3},
    {"Country": "Uruguay", "Most Recent Year": 2022, "Most Recent Value": 40.6},
    {"Country": "Uzbekistan", "Most Recent Year": 2022, "Most Recent Value": 31.2},
    {"Country": "Vanuatu", "Most Recent Year": 2019, "Most Recent Value": 32.3},
    {"Country": "Venezuela, RB", "Most Recent Year": 2006, "Most Recent Value": 44.7},
    {"Country": "Viet Nam", "Most Recent Year": 2022, "Most Recent Value": 36.1},
    {"Country": "Virgin Islands (U.S.)", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "West Bank and Gaza", "Most Recent Year": 2016, "Most Recent Value": 33.7},
    {"Country": "Yemen, Rep.", "Most Recent Year": 2014, "Most Recent Value": 36.7},
    {"Country": "Zambia", "Most Recent Year": 2022, "Most Recent Value": 51.5},
    {"Country": "Zimbabwe", "Most Recent Year": 2019, "Most Recent Value": 50.3},
    {"Country": "World", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Arab World", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Caribbean small states", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Central Europe and the Baltics", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "East Asia & Pacific", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "East Asia & Pacific (excluding high income)", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Euro area", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Europe & Central Asia", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Europe & Central Asia (excluding high income)", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "European Union", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Fragile and conflict affected situations", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Heavily indebted poor countries (HIPC)", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Latin America & Caribbean", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Latin America & Caribbean (excluding high income)", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Least developed countries: UN classification", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Middle East & North Africa", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Middle East & North Africa (excluding high income)", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "North America", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "OECD members", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Other small states", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Pacific island small states", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Small states", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "South Asia", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Sub-Saharan Africa", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Sub-Saharan Africa (excluding high income)", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "High income", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Low & middle income", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Low income", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Lower middle income", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Middle income", "Most Recent Year": "", "Most Recent Value": ""},
    {"Country": "Upper middle income", "Most Recent Year": "", "Most Recent Value": ""}
]

# Create a DataFrame
df = pd.DataFrame(data)

# Save to CSV file
df.to_csv('gini_coefficients.csv', index=False)

print("CSV file 'gini_coefficients.csv' has been created successfully!")